steps:
  # Step 1: Deploy the Python Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'teste-teste'          # Change to your desired function name
      - '--runtime=python314'          # Choose your Python version (e.g., python310, python311)
      - '--region=us-central1'         # Replace with your target GCP region
      - '--source=.'                   # Looks for code in the root directory
      - '--entry-point=main'           # The name of the Python function inside your main.py
      - '--trigger-http'               # Makes the function accessible via HTTP
      - '--allow-unauthenticated'      # Allows public internet access (remove if you want it private)

options:
  logging: CLOUD_LOGGING_ONLY          # Streamlines logging directly to Cloud Logging
